/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package morrales.UI;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import morrales.BL.ResolverProblema;

/**
 *
 * @author roand_000
 */
public class SubirArchivoGUI extends javax.swing.JPanel {

    /**
     * Creates new form SubirArchivoGUI
     */
    public SubirArchivoGUI() {
        initComponents();
        rb_default.setSelected(true);
        for(int i=0;i<panelbb.getComponents().length;i++) 
        {
            panelbb.getComponent(i).setEnabled(false);    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fl_buscarRuta = new javax.swing.JFileChooser();
        jLabel2 = new javax.swing.JLabel();
        gbox_bbrule = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        panelbb = new javax.swing.JPanel();
        bt_calcular = new javax.swing.JButton();
        rb_node_gapselect = new javax.swing.JRadioButton();
        rb_node_firstselect = new javax.swing.JRadioButton();
        rb_node_rangeselect = new javax.swing.JRadioButton();
        rb_node_pseudocostsselect = new javax.swing.JRadioButton();
        rb_node_pseudononintselect = new javax.swing.JRadioButton();
        rb_node_pseudorationselect = new javax.swing.JRadioButton();
        rb_node_userselect = new javax.swing.JRadioButton();
        rb_default = new javax.swing.JRadioButton();
        rb_node_fractionselect = new javax.swing.JRadioButton();
        lb_subirArchivo = new javax.swing.JLabel();
        sp_areaDeRespuesta = new javax.swing.JSplitPane();
        pn_areaRequerimiento = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lb_requerimiento = new javax.swing.JLabel();
        lb_cantdecajas = new javax.swing.JLabel();
        lb_volMorrales = new javax.swing.JLabel();
        lb_pesoDeMorrales = new javax.swing.JLabel();
        tb_cantDeCajas = new javax.swing.JTextField();
        tb_volMorrales = new javax.swing.JTextField();
        tb_pesoDeMorrales = new javax.swing.JTextField();
        sc_requerimiento = new javax.swing.JScrollPane();
        ta_requerimiento = new javax.swing.JTable();
        pn_areaSolucionCantidadMorrales = new javax.swing.JPanel();
        sp_areaRespuestaCantidadMorrales = new javax.swing.JSplitPane();
        pn_areaSolucion = new javax.swing.JPanel();
        pn_solucionCantidadMorrales = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tb_numeroNodosCantMorrales = new javax.swing.JTextField();
        tb_cantidadIteracionesCantMorrales = new javax.swing.JTextField();
        tb_cantidadVariablesCantMorrales = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tb_tiempoDeEjecucionCantMorrales = new javax.swing.JTextField();
        sc_solucionCantidadMorrales = new javax.swing.JScrollPane();
        ta_solucionCantidadMorrales = new javax.swing.JTable();
        lb_numDeMorrales = new javax.swing.JLabel();
        tb_numDeMorrales = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        sc_distribucionCantidadMorrales = new javax.swing.JScrollPane();
        ta_solucionDistribucionEquilibrada = new javax.swing.JTable();
        pn_solucionCantidadMorrales1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tb_numeroNodosDistriEquilibrada = new javax.swing.JTextField();
        tb_cantidadIteracionesDistriEquilibrada = new javax.swing.JTextField();
        tb_cantidadVariablesDistriEquilibrada = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tb_tiempoDeEjecucionDistriEquilibrada = new javax.swing.JTextField();
        tb_ruta = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setMinimumSize(new java.awt.Dimension(817, 676));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/morrales/UI/imagenes/subirArchivoImagen.png"))); // NOI18N
        jButton1.setIconTextGap(3);
        jButton1.setInheritsPopupMenu(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panelbb.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelbb.setEnabled(false);

        bt_calcular.setText("Calcular");
        bt_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_calcularActionPerformed(evt);
            }
        });

        gbox_bbrule.add(rb_node_gapselect);
        rb_node_gapselect.setText("NODE_GAPSELECT");

        gbox_bbrule.add(rb_node_firstselect);
        rb_node_firstselect.setText("NODE_FIRSTSELECT ");

        gbox_bbrule.add(rb_node_rangeselect);
        rb_node_rangeselect.setText("NODE_RANGESELECT");

        gbox_bbrule.add(rb_node_pseudocostsselect);
        rb_node_pseudocostsselect.setText("NODE_PSEUDOCOSTSELECT ");

        gbox_bbrule.add(rb_node_pseudononintselect);
        rb_node_pseudononintselect.setText("NODE_PSEUDONONINTSELECT ");

        gbox_bbrule.add(rb_node_pseudorationselect);
        rb_node_pseudorationselect.setText("NODE_PSEUDORATIOSELECT ");

        gbox_bbrule.add(rb_node_userselect);
        rb_node_userselect.setText("NODE_USERSELECT");

        gbox_bbrule.add(rb_default);
        rb_default.setText("DEFAULT");

        gbox_bbrule.add(rb_node_fractionselect);
        rb_node_fractionselect.setText("NODE_FRACTIONSELECT");

        javax.swing.GroupLayout panelbbLayout = new javax.swing.GroupLayout(panelbb);
        panelbb.setLayout(panelbbLayout);
        panelbbLayout.setHorizontalGroup(
            panelbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbbLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbbLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_calcular))
                    .addGroup(panelbbLayout.createSequentialGroup()
                        .addGroup(panelbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelbbLayout.createSequentialGroup()
                                .addComponent(rb_default)
                                .addGap(18, 18, 18)
                                .addComponent(rb_node_firstselect))
                            .addComponent(rb_node_pseudononintselect, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_node_rangeselect)
                            .addComponent(rb_node_gapselect))
                        .addGap(10, 10, 10)
                        .addGroup(panelbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_node_pseudocostsselect, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_node_pseudorationselect))
                        .addGap(18, 18, 18)
                        .addGroup(panelbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_node_fractionselect)
                            .addComponent(rb_node_userselect, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        panelbbLayout.setVerticalGroup(
            panelbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_node_pseudocostsselect)
                    .addComponent(rb_node_rangeselect)
                    .addComponent(rb_node_firstselect)
                    .addComponent(rb_default)
                    .addComponent(rb_node_userselect))
                .addGroup(panelbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbbLayout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(bt_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelbbLayout.createSequentialGroup()
                        .addGroup(panelbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_node_pseudononintselect)
                            .addComponent(rb_node_gapselect)
                            .addComponent(rb_node_pseudorationselect)
                            .addComponent(rb_node_fractionselect))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        lb_subirArchivo.setText("Subir Archivo");

        sp_areaDeRespuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sp_areaDeRespuesta.setOneTouchExpandable(true);
        sp_areaDeRespuesta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sp_areaDeRespuestaFocusGained(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_requerimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_requerimiento.setText("Requerimiento");

        lb_cantdecajas.setText("Cantidad de cajas");

        lb_volMorrales.setText("Volumen que soportan los morrales");

        lb_pesoDeMorrales.setText("Peso que soportan los Morrales");

        tb_cantDeCajas.setEditable(false);

        tb_volMorrales.setEditable(false);

        tb_pesoDeMorrales.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_volMorrales)
                            .addComponent(lb_cantdecajas)
                            .addComponent(lb_pesoDeMorrales, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tb_pesoDeMorrales, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(tb_volMorrales)
                            .addComponent(tb_cantDeCajas)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_requerimiento)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lb_requerimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cantdecajas)
                    .addComponent(tb_cantDeCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_volMorrales)
                    .addComponent(tb_volMorrales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_pesoDeMorrales)
                    .addComponent(tb_pesoDeMorrales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ta_requerimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Caja", "Volumen", "Peso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ta_requerimiento.setEnabled(false);
        sc_requerimiento.setViewportView(ta_requerimiento);

        javax.swing.GroupLayout pn_areaRequerimientoLayout = new javax.swing.GroupLayout(pn_areaRequerimiento);
        pn_areaRequerimiento.setLayout(pn_areaRequerimientoLayout);
        pn_areaRequerimientoLayout.setHorizontalGroup(
            pn_areaRequerimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_areaRequerimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_areaRequerimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_areaRequerimientoLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sc_requerimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_areaRequerimientoLayout.setVerticalGroup(
            pn_areaRequerimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_areaRequerimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sc_requerimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );

        sp_areaDeRespuesta.setLeftComponent(pn_areaRequerimiento);

        sp_areaRespuestaCantidadMorrales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sp_areaRespuestaCantidadMorrales.setOneTouchExpandable(true);

        pn_solucionCantidadMorrales.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Solucion (Cantidad de Morrales)");

        jLabel1.setText("Numero de nodos");

        jLabel4.setText("Cantidad de iteraciones");

        jLabel5.setText("Cantidad de variables generadas");

        tb_numeroNodosCantMorrales.setEditable(false);

        tb_cantidadIteracionesCantMorrales.setEditable(false);
        tb_cantidadIteracionesCantMorrales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_cantidadIteracionesCantMorralesActionPerformed(evt);
            }
        });

        tb_cantidadVariablesCantMorrales.setEditable(false);

        jLabel6.setText("Tiempo de ejecucion");

        tb_tiempoDeEjecucionCantMorrales.setEditable(false);

        javax.swing.GroupLayout pn_solucionCantidadMorralesLayout = new javax.swing.GroupLayout(pn_solucionCantidadMorrales);
        pn_solucionCantidadMorrales.setLayout(pn_solucionCantidadMorralesLayout);
        pn_solucionCantidadMorralesLayout.setHorizontalGroup(
            pn_solucionCantidadMorralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_solucionCantidadMorralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_solucionCantidadMorralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_solucionCantidadMorralesLayout.createSequentialGroup()
                        .addGroup(pn_solucionCantidadMorralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(pn_solucionCantidadMorralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_solucionCantidadMorralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tb_cantidadVariablesCantMorrales, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tb_cantidadIteracionesCantMorrales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(tb_numeroNodosCantMorrales, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(tb_tiempoDeEjecucionCantMorrales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_solucionCantidadMorralesLayout.setVerticalGroup(
            pn_solucionCantidadMorralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_solucionCantidadMorralesLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_solucionCantidadMorralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tb_numeroNodosCantMorrales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_solucionCantidadMorralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tb_cantidadIteracionesCantMorrales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_solucionCantidadMorralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tb_cantidadVariablesCantMorrales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_solucionCantidadMorralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tb_tiempoDeEjecucionCantMorrales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ta_solucionCantidadMorrales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ta_solucionCantidadMorrales.setToolTipText("");
        ta_solucionCantidadMorrales.setEnabled(false);
        sc_solucionCantidadMorrales.setViewportView(ta_solucionCantidadMorrales);

        lb_numDeMorrales.setText("El número óptimo de morrales es:");

        tb_numDeMorrales.setEditable(false);

        javax.swing.GroupLayout pn_areaSolucionLayout = new javax.swing.GroupLayout(pn_areaSolucion);
        pn_areaSolucion.setLayout(pn_areaSolucionLayout);
        pn_areaSolucionLayout.setHorizontalGroup(
            pn_areaSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_areaSolucionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_areaSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_areaSolucionLayout.createSequentialGroup()
                        .addComponent(pn_solucionCantidadMorrales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sc_solucionCantidadMorrales, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_areaSolucionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb_numDeMorrales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_numDeMorrales, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pn_areaSolucionLayout.setVerticalGroup(
            pn_areaSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_areaSolucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_solucionCantidadMorrales, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sc_solucionCantidadMorrales, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_areaSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_numDeMorrales)
                    .addComponent(tb_numDeMorrales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        sp_areaRespuestaCantidadMorrales.setLeftComponent(pn_areaSolucion);

        ta_solucionDistribucionEquilibrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ta_solucionDistribucionEquilibrada.setToolTipText("");
        ta_solucionDistribucionEquilibrada.setEnabled(false);
        sc_distribucionCantidadMorrales.setViewportView(ta_solucionDistribucionEquilibrada);

        pn_solucionCantidadMorrales1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Solucion (Distribución equilibrada)");

        jLabel8.setText("Numero de nodos");

        jLabel9.setText("Cantidad de iteraciones");

        jLabel10.setText("Cantidad de variables generadas");

        tb_numeroNodosDistriEquilibrada.setEditable(false);

        tb_cantidadIteracionesDistriEquilibrada.setEditable(false);
        tb_cantidadIteracionesDistriEquilibrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_cantidadIteracionesDistriEquilibradaActionPerformed(evt);
            }
        });

        tb_cantidadVariablesDistriEquilibrada.setEditable(false);

        jLabel11.setText("Tiempo de ejecucion");

        tb_tiempoDeEjecucionDistriEquilibrada.setEditable(false);

        javax.swing.GroupLayout pn_solucionCantidadMorrales1Layout = new javax.swing.GroupLayout(pn_solucionCantidadMorrales1);
        pn_solucionCantidadMorrales1.setLayout(pn_solucionCantidadMorrales1Layout);
        pn_solucionCantidadMorrales1Layout.setHorizontalGroup(
            pn_solucionCantidadMorrales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_solucionCantidadMorrales1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_solucionCantidadMorrales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(pn_solucionCantidadMorrales1Layout.createSequentialGroup()
                        .addGroup(pn_solucionCantidadMorrales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(pn_solucionCantidadMorrales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tb_numeroNodosDistriEquilibrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(tb_cantidadIteracionesDistriEquilibrada, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tb_cantidadVariablesDistriEquilibrada, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tb_tiempoDeEjecucionDistriEquilibrada, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_solucionCantidadMorrales1Layout.setVerticalGroup(
            pn_solucionCantidadMorrales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_solucionCantidadMorrales1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_solucionCantidadMorrales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tb_numeroNodosDistriEquilibrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_solucionCantidadMorrales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tb_cantidadIteracionesDistriEquilibrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_solucionCantidadMorrales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tb_cantidadVariablesDistriEquilibrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_solucionCantidadMorrales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tb_tiempoDeEjecucionDistriEquilibrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pn_solucionCantidadMorrales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sc_distribucionCantidadMorrales, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_solucionCantidadMorrales1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sc_distribucionCantidadMorrales, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );

        sp_areaRespuestaCantidadMorrales.setRightComponent(jPanel2);

        javax.swing.GroupLayout pn_areaSolucionCantidadMorralesLayout = new javax.swing.GroupLayout(pn_areaSolucionCantidadMorrales);
        pn_areaSolucionCantidadMorrales.setLayout(pn_areaSolucionCantidadMorralesLayout);
        pn_areaSolucionCantidadMorralesLayout.setHorizontalGroup(
            pn_areaSolucionCantidadMorralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_areaRespuestaCantidadMorrales, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        pn_areaSolucionCantidadMorralesLayout.setVerticalGroup(
            pn_areaSolucionCantidadMorralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_areaSolucionCantidadMorralesLayout.createSequentialGroup()
                .addComponent(sp_areaRespuestaCantidadMorrales)
                .addContainerGap())
        );

        sp_areaDeRespuesta.setRightComponent(pn_areaSolucionCantidadMorrales);

        tb_ruta.setEditable(false);
        tb_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_rutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_areaDeRespuesta)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_subirArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tb_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tb_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_subirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp_areaDeRespuesta))
        );
    }// </editor-fold>//GEN-END:initComponents
        ResolverProblema resolver;
        LlenarTablas llenarTab;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Cantidad Morrales
        tb_cantidadIteracionesCantMorrales.setText("");
        tb_cantidadVariablesCantMorrales.setText("");
        tb_numeroNodosCantMorrales.setText("");
        tb_numDeMorrales.setText("");
        tb_tiempoDeEjecucionCantMorrales.setText("");
        
        //Distribucion equilibrada
        tb_cantidadIteracionesDistriEquilibrada.setText("");
        tb_cantidadVariablesDistriEquilibrada.setText("");
        tb_numeroNodosDistriEquilibrada.setText("");
        tb_tiempoDeEjecucionDistriEquilibrada.setText("");
            
         try {
            fl_buscarRuta.showOpenDialog(this);
         
         if (fl_buscarRuta.getSelectedFile()!=null)
         {
             for(int i=0;i<panelbb.getComponents().length;i++) {
                panelbb.getComponent(i).setEnabled(true);
             }
         }
    
        llenarTab=new LlenarTablas(fl_buscarRuta.getSelectedFile().getPath());
        resolver=new ResolverProblema(fl_buscarRuta.getSelectedFile().getPath());
        tb_ruta.setText(fl_buscarRuta.getSelectedFile().getPath());
        String pattern = "###.###";
        DecimalFormat decimalFormat = new DecimalFormat(pattern);
        tb_cantDeCajas.setText(""+Math.round(resolver.getPropiedades().get(0)));
        tb_volMorrales.setText(decimalFormat.format(resolver.getPropiedades().get(1)));
        tb_pesoDeMorrales.setText(decimalFormat.format(resolver.getPropiedades().get(2)));
        llenarTab.llenarTablarRequerimiento(ta_requerimiento);
        ta_solucionCantidadMorrales.setModel(new DefaultTableModel());
        ta_solucionDistribucionEquilibrada.setModel(new DefaultTableModel());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un archivo");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calcularActionPerformed
        
        llenarTab=new LlenarTablas(fl_buscarRuta.getSelectedFile().getPath());
        if (fl_buscarRuta.getSelectedFile()!=null)
        {
            
        boolean factible=true;
        
        
            if (rb_node_firstselect.isSelected())
            {
                factible=llenarTab.llenarTablaCantidadMorrales(ta_solucionCantidadMorrales,0);
                llenarTab.llenarTablaDistEquilibradaMorrales(ta_solucionDistribucionEquilibrada,0);
            }
            else if (rb_node_gapselect.isSelected())
            {
                factible=llenarTab.llenarTablaCantidadMorrales(ta_solucionCantidadMorrales,1);
                llenarTab.llenarTablaDistEquilibradaMorrales(ta_solucionDistribucionEquilibrada,1);
            }
            else  if (rb_node_rangeselect.isSelected())
            {
                factible=llenarTab.llenarTablaCantidadMorrales(ta_solucionCantidadMorrales,2);
                llenarTab.llenarTablaDistEquilibradaMorrales(ta_solucionDistribucionEquilibrada,2);
            }
            else if (rb_node_fractionselect.isSelected())
            {
                factible=llenarTab.llenarTablaCantidadMorrales(ta_solucionCantidadMorrales,3);
                llenarTab.llenarTablaDistEquilibradaMorrales(ta_solucionDistribucionEquilibrada,3);
            }
            else if (rb_node_pseudocostsselect.isSelected())
            {
                factible=llenarTab.llenarTablaCantidadMorrales(ta_solucionCantidadMorrales,4);
                llenarTab.llenarTablaDistEquilibradaMorrales(ta_solucionDistribucionEquilibrada,4);
            }
            else if (rb_node_pseudononintselect.isSelected())
            {
                factible=llenarTab.llenarTablaCantidadMorrales(ta_solucionCantidadMorrales,5);
                llenarTab.llenarTablaDistEquilibradaMorrales(ta_solucionDistribucionEquilibrada,5);
            }
            else if (rb_node_pseudorationselect.isSelected())
            {
                factible=llenarTab.llenarTablaCantidadMorrales(ta_solucionCantidadMorrales,6);
                llenarTab.llenarTablaDistEquilibradaMorrales(ta_solucionDistribucionEquilibrada,6);
            }
            else if (rb_node_userselect.isSelected())
            {
                factible=llenarTab.llenarTablaCantidadMorrales(ta_solucionCantidadMorrales,7);
                llenarTab.llenarTablaDistEquilibradaMorrales(ta_solucionDistribucionEquilibrada,7);
            }
            else if (rb_default.isSelected())
            {
                factible=llenarTab.llenarTablaCantidadMorrales(ta_solucionCantidadMorrales,8);
                llenarTab.llenarTablaDistEquilibradaMorrales(ta_solucionDistribucionEquilibrada,8);
            }
            
            if (factible){
                //tabla de cantidad de morrales
            tb_cantidadIteracionesCantMorrales.setText(String.valueOf(llenarTab.getCantidadIteracionesCantMorrales()));
            tb_cantidadVariablesCantMorrales.setText(""+llenarTab.getCantidadVariablesCantMorrales());
            tb_numeroNodosCantMorrales.setText(String.valueOf(llenarTab.getCantidadNodosCantMorrales()));
            tb_numDeMorrales.setText(""+Math.round(llenarTab.getNumeroOptimoMorrales()));
            tb_tiempoDeEjecucionCantMorrales.setText(""+llenarTab.getTiempoDeEjecucionCantMorrales()+" (ms)");
            
            //tabla de distribucion
            tb_cantidadIteracionesDistriEquilibrada.setText(String.valueOf(llenarTab.getCantidadIteracionesDistMorrales()));
            tb_cantidadVariablesDistriEquilibrada.setText(""+llenarTab.getCantidadVariablesDistMorrales());
            tb_numeroNodosDistriEquilibrada.setText(String.valueOf(llenarTab.getCantidadNodosDistMorrales()));
            tb_tiempoDeEjecucionDistriEquilibrada.setText(""+llenarTab.getTiempoDeEjecucionDistMorrales()+" (ms)");
            }
            else 
                JOptionPane.showMessageDialog(null,"La entrada no es factible","Error de factibilidad",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_calcularActionPerformed

    private void sp_areaDeRespuestaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sp_areaDeRespuestaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_sp_areaDeRespuestaFocusGained

    private void tb_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_rutaActionPerformed

    private void tb_cantidadIteracionesCantMorralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_cantidadIteracionesCantMorralesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_cantidadIteracionesCantMorralesActionPerformed

    private void tb_cantidadIteracionesDistriEquilibradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_cantidadIteracionesDistriEquilibradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_cantidadIteracionesDistriEquilibradaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_calcular;
    private javax.swing.JFileChooser fl_buscarRuta;
    private javax.swing.ButtonGroup gbox_bbrule;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_cantdecajas;
    private javax.swing.JLabel lb_numDeMorrales;
    private javax.swing.JLabel lb_pesoDeMorrales;
    private javax.swing.JLabel lb_requerimiento;
    private javax.swing.JLabel lb_subirArchivo;
    private javax.swing.JLabel lb_volMorrales;
    private javax.swing.JPanel panelbb;
    private javax.swing.JPanel pn_areaRequerimiento;
    private javax.swing.JPanel pn_areaSolucion;
    private javax.swing.JPanel pn_areaSolucionCantidadMorrales;
    private javax.swing.JPanel pn_solucionCantidadMorrales;
    private javax.swing.JPanel pn_solucionCantidadMorrales1;
    private javax.swing.JRadioButton rb_default;
    private javax.swing.JRadioButton rb_node_firstselect;
    private javax.swing.JRadioButton rb_node_fractionselect;
    private javax.swing.JRadioButton rb_node_gapselect;
    private javax.swing.JRadioButton rb_node_pseudocostsselect;
    private javax.swing.JRadioButton rb_node_pseudononintselect;
    private javax.swing.JRadioButton rb_node_pseudorationselect;
    private javax.swing.JRadioButton rb_node_rangeselect;
    private javax.swing.JRadioButton rb_node_userselect;
    private javax.swing.JScrollPane sc_distribucionCantidadMorrales;
    private javax.swing.JScrollPane sc_requerimiento;
    private javax.swing.JScrollPane sc_solucionCantidadMorrales;
    private javax.swing.JSplitPane sp_areaDeRespuesta;
    private javax.swing.JSplitPane sp_areaRespuestaCantidadMorrales;
    private javax.swing.JTable ta_requerimiento;
    private javax.swing.JTable ta_solucionCantidadMorrales;
    private javax.swing.JTable ta_solucionDistribucionEquilibrada;
    private javax.swing.JTextField tb_cantDeCajas;
    private javax.swing.JTextField tb_cantidadIteracionesCantMorrales;
    private javax.swing.JTextField tb_cantidadIteracionesDistriEquilibrada;
    private javax.swing.JTextField tb_cantidadVariablesCantMorrales;
    private javax.swing.JTextField tb_cantidadVariablesDistriEquilibrada;
    private javax.swing.JTextField tb_numDeMorrales;
    private javax.swing.JTextField tb_numeroNodosCantMorrales;
    private javax.swing.JTextField tb_numeroNodosDistriEquilibrada;
    private javax.swing.JTextField tb_pesoDeMorrales;
    private javax.swing.JTextField tb_ruta;
    private javax.swing.JTextField tb_tiempoDeEjecucionCantMorrales;
    private javax.swing.JTextField tb_tiempoDeEjecucionDistriEquilibrada;
    private javax.swing.JTextField tb_volMorrales;
    // End of variables declaration//GEN-END:variables
}
